"""
Polynomial Prediction Functions for IMT2024042 (VAR1 and VAR2)

Provides pure NumPy/Python evaluation functions for the exact fitted polynomials:
- VAR1: Degree 5 polynomial across 6 operational parameters
- VAR2: Degree 11 polynomial across 3 spatial coordinates

NOTE: Coefficients are stored in the original (unscaled) feature space.
During training, StandardScaler is applied to polynomial features before
fitting Ridge regression.  The saved coefficients have been transformed
back to the unscaled monomial space via:
    coef_unscaled[i] = coef_scaled[i] / scale[i]
    intercept_unscaled = intercept_scaled - sum(coef_scaled[i] * mean[i] / scale[i])
This means these functions evaluate directly on raw input values.
"""
import numpy as np
import os

# ---------- Load saved polynomial parameters ----------
_CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
_OUTPUT_DIR = os.path.join(os.path.dirname(_CURRENT_DIR), "outputs")

# New per-variant files (generated by updated training scripts)
_VAR1_PATH = os.path.join(_OUTPUT_DIR, "fitted_var1.npz")
_VAR2_PATH = os.path.join(_OUTPUT_DIR, "fitted_var2.npz")
# Legacy combined file (backward compatibility)
_LEGACY_PATH = os.path.join(_OUTPUT_DIR, "fitted_polynomials.npz")

if os.path.exists(_VAR1_PATH):
    _d1 = np.load(_VAR1_PATH)
    INTERCEPT_VAR1 = float(_d1['intercept'])
    COEFS_VAR1 = _d1['coefs']
    POWERS_VAR1 = _d1['powers']
elif os.path.exists(_LEGACY_PATH):
    _data = np.load(_LEGACY_PATH)
    INTERCEPT_VAR1 = float(_data['inter1'])
    COEFS_VAR1 = _data['coefs1']
    POWERS_VAR1 = _data['powers1']
else:
    raise FileNotFoundError(
        f"No fitted VAR1 data found.  Run training first.\n"
        f"Checked: {_VAR1_PATH}, {_LEGACY_PATH}"
    )

if os.path.exists(_VAR2_PATH):
    _d2 = np.load(_VAR2_PATH)
    INTERCEPT_VAR2 = float(_d2['intercept'])
    COEFS_VAR2 = _d2['coefs']
    POWERS_VAR2 = _d2['powers']
elif os.path.exists(_LEGACY_PATH):
    _data = np.load(_LEGACY_PATH)
    INTERCEPT_VAR2 = float(_data['inter2'])
    COEFS_VAR2 = _data['coefs2']
    POWERS_VAR2 = _data['powers2']
else:
    raise FileNotFoundError(
        f"No fitted VAR2 data found.  Run training first.\n"
        f"Checked: {_VAR2_PATH}, {_LEGACY_PATH}"
    )

VAR1_FEATURE_NAMES = ['x1', 'x2', 'x3', 'x4', 'x5', 'x6']
VAR2_FEATURE_NAMES = ['x1', 'x2', 'x3']


def predict_var1(x1, x2, x3, x4, x5, x6):
    """
    Evaluate the fitted Degree-5 Polynomial for VAR1 (Power Plant Steam Turbine).

    Parameters
    ----------
    x1 : float or np.ndarray
        High-pressure steam valve adjustment (in [-1, 1])
    x2 : float or np.ndarray
        Condenser coolant flow rate adjustment (in [-1, 1])
    x3 : float or np.ndarray
        Re-injection pump hydraulic pressure (in [-1, 1])
    x4 : float or np.ndarray
        Turbine blade pitch angle (in [-1, 1])
    x5 : float or np.ndarray
        Non-condensable gas exhaust valve rate (in [-1, 1])
    x6 : float or np.ndarray
        Steam inlet pressure adjustment (in [-1, 1])

    Returns
    -------
    float or np.ndarray
        Predicted Net Power Score (y)
    """
    x = np.array([x1, x2, x3, x4, x5, x6], dtype=float)
    if x.ndim == 1:
        monomials = np.prod(x ** POWERS_VAR1, axis=1)
        return float(INTERCEPT_VAR1 + np.dot(monomials, COEFS_VAR1))
    else:
        X = x.T
        return predict_var1_matrix(X)


def predict_var1_matrix(X):
    """Vectorized batch prediction for VAR1 on a 2D array of shape (N, 6)."""
    X = np.asarray(X, dtype=float)
    monomials = np.prod(X[:, None, :] ** POWERS_VAR1[None, :, :], axis=2)
    return INTERCEPT_VAR1 + np.dot(monomials, COEFS_VAR1)


def predict_var2(x1, x2, x3):
    """
    Evaluate the fitted Degree-11 Polynomial for VAR2 (Thermal Reservoir Mapping).

    Parameters
    ----------
    x1 : float or np.ndarray
        East-West coordinate offset (in [-1, 1])
    x2 : float or np.ndarray
        North-South coordinate offset (in [-1, 1])
    x3 : float or np.ndarray
        Vertical depth offset (in [-1, 1])

    Returns
    -------
    float or np.ndarray
        Predicted Thermal Anomaly Score (y)
    """
    x = np.array([x1, x2, x3], dtype=float)
    if x.ndim == 1:
        monomials = np.prod(x ** POWERS_VAR2, axis=1)
        return float(INTERCEPT_VAR2 + np.dot(monomials, COEFS_VAR2))
    else:
        X = x.T
        return predict_var2_matrix(X)


def predict_var2_matrix(X):
    """Vectorized batch prediction for VAR2 on a 2D array of shape (N, 3)."""
    X = np.asarray(X, dtype=float)
    monomials = np.prod(X[:, None, :] ** POWERS_VAR2[None, :, :], axis=2)
    return INTERCEPT_VAR2 + np.dot(monomials, COEFS_VAR2)


def get_polynomial_terms(var='var1'):
    """Return a list of dicts with all terms, exponents, and weights."""
    if var == 'var1':
        feats = VAR1_FEATURE_NAMES
        powers = POWERS_VAR1
        coefs = COEFS_VAR1
        inter = INTERCEPT_VAR1
    else:
        feats = VAR2_FEATURE_NAMES
        powers = POWERS_VAR2
        coefs = COEFS_VAR2
        inter = INTERCEPT_VAR2

    terms = []
    for p, c in zip(powers, coefs):
        parts = []
        for feat_name, power in zip(feats, p):
            if power == 1:
                parts.append(feat_name)
            elif power > 1:
                parts.append(f"{feat_name}^{power}")
        term_str = " * ".join(parts) if parts else "1"
        terms.append({
            'term': term_str,
            'weight': float(c),
            'degree': int(sum(p))
        })
    return inter, terms


def print_top_terms(var='var1', top_n=15):
    """Print the intercept and top N most influential polynomial terms."""
    inter, terms = get_polynomial_terms(var)
    sorted_terms = sorted(terms, key=lambda t: abs(t['weight']), reverse=True)
    name = "VAR1 (Degree 5)" if var == 'var1' else "VAR2 (Degree 11)"
    print(f"\n{'='*60}")
    print(f"  {name} Polynomial Representation")
    print(f"{'='*60}")
    print(f"  Intercept w0 = {inter:+.6f}\n")
    print(f"  Top {top_n} Terms by Weight Magnitude:")
    for i, t in enumerate(sorted_terms[:top_n], 1):
        print(f"   {i:2d}. {t['weight']:+9.6f} * ({t['term']})  [deg {t['degree']}]")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    y1_example = predict_var1(0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
    print(f"VAR1 at origin (0,0,0,0,0,0) -> y = {y1_example:.6f} "
          f"(matches intercept: {INTERCEPT_VAR1:.6f})")

    y2_example = predict_var2(0.0, 0.0, 0.0)
    print(f"VAR2 at origin (0,0,0) -> y = {y2_example:.6f} "
          f"(matches intercept: {INTERCEPT_VAR2:.6f})")

    print_top_terms('var1', top_n=10)
    print_top_terms('var2', top_n=10)
